### ISSUE TITLE
Process _sv 2.1 Activity exercise videos

### ISSUE THREAD

**Issue by jim1001** [jim1001/DemPower-Issues#168]
Therese,

Have done these as best I could - the videos you gave me were all different sizes and aspect ratios. I'm sure I can hear a young girl in the background on one too!

They are [here ](https://www.dropbox.com/sh/benrgo9v1jmieks/AAAcuY2ItUMuiADgFt6H_mJ4a?dl=0)for upload to tablet.

Anyway, the exercises are clear enough for someone to follow.

The screen title  for these videos is _NHS exercise video_ - if you want a different title for _sv we can put an entry in the sv.yml file. Let me know.

**Comment by thebi84** [comment]
Thanks!
yes they are ok:) The first video is named "Sittande midjetvist", the second video is named "stå på ett ben", the third is named "Bryggan" and the last is named "Bordet". Could you do these as screen titles?
Do you want me to do text to the videos as well?

**Comment by jim1001** [comment]
> The first video is named "Sittande midjetvist", the second video is named "stå på ett ben", the third is named "Bryggan" and the last is named "Bordet". Could you do these as screen titles?

No - they all need to have the same general title on the video screen. The English title is  _NHS exercise video_ - so perhaps just _Exercise Video_ in Swedish would do?

On the screen _2.1 Traning videos_  (reached by the _Ga till actvitet_ button) you can have different titles as links. Those are set in sv.yml. Are you happy with those or do you want them changing to the names you say above?

> Do you want me to do text to the videos as well?

Up to you - there are no transcripts for the _en exercise videos...

**Comment by thebi84** [comment]
Ok. In Swedish just "Övningar"

yes please change them to the above.

Ok, I think I will produce text to them.

**Comment by jim1001** [comment]
> Ok. In Swedish just "Övningar"

Done but not uploaded yet.

> yes please change them to the above.

So you want the link to be the title of the video? That's what I did at first for the English version. Then Reena said she wanted it changing because the video titles wouldn't mean much to people, e.g. "Table Top". She wanted the links to describe the exercise better. Just letting you know that - it's no problem either way for me.

**Comment by jim1001** [comment]
Therese - please can you confirm you definitely want the links changed to e.g. _Sittande midjetvist_ etc, i.e. the names given to the exercise on the videos rather than a description of the exercise, e.g. Swedish for _Keeping a flexible spine_ like we have on the English version. Thanks.

**Comment by thebi84** [comment]
No, when I rethink it I think it will be better with.
1 "Bibehålla en flexibel ryggrad"
2 "Träna balans och stabilitet"
3 "Träna lår och stjärtmuskler"
4 "Träna hållning och balans"

Thanks
________________________________
Från: jim1001 <notifications@github.com>
Skickat: den 4 maj 2018 18:27:33
Till: jim1001/DemPower-Issues
Kopia: Therese Bielsten; Assign
Ämne: Re: [jim1001/DemPower-Issues] Process _sv 2.1 Activity exercise videos (#168)


Therese - please can you confirm you definitely want the links changed to e.g. Sittande midjetvist etc, i.e. the names given to the exercise on the videos rather than a description of the exercise, e.g. Swedish for Keeping a flexible spine like we have on the English version. Thanks.

**Comment by jim1001** [comment]
All changes made - install [DemPower_sv_v159.apk](https://www.dropbox.com/s/r5m7ut3tt9zcjno/DemPower_sv_v159.apk?dl=0) to see.

**Comment by jim1001** [comment]
Looks OK on my tablet. Had no more comments so closing the issue.
